// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erxdghcpstikjekomtol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeGRnaGNwc3Rpa2pla29tdG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTAwNjYsImV4cCI6MjA2NTUyNjA2Nn0.gxqdibJ-FiPHtxqCsC4jeqlsVX2Y0DmeR5dizuPn1sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);